[build]
builder = "nixpacks"

[build.nixpacks]
installCmds = ["rm -rf node_modules", "npm install --legacy-peer-deps"]
buildCmds = ["npm run build"]

[deploy]
startCommand = "npx serve -s dist -l ${PORT:-3000}"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

